// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class CommentsAttractionImage
    {
        public int Id { get; set; }
        public int CommentsAttractionId { get; set; }
        public string Image { get; set; }

        public virtual CommentsAttraction CommentsAttraction { get; set; }
    }
}