// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class CommentAccommodationLike
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int CommentsAccommodationId { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual CommentsAccommodation CommentsAccommodation { get; set; }
        public virtual Member Member { get; set; }
    }
}