// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class OrderActivitiesDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public int ActivityProductId { get; set; }
        public DateTime Date { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual ActivityProduct ActivityProduct { get; set; }
        public virtual Order Order { get; set; }
    }
}