// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class PackageTour
    {
        public PackageTour()
        {
            Activities = new HashSet<Activity>();
            Attractions = new HashSet<Attraction>();
            ExtraServices = new HashSet<ExtraService>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public int PackageCouponId { get; set; }

        public virtual PackageCoupon PackageCoupon { get; set; }

        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Attraction> Attractions { get; set; }
        public virtual ICollection<ExtraService> ExtraServices { get; set; }
    }
}