// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class ReportedAttractionComment
    {
        public int Id { get; set; }
        public int CommentAttractionId { get; set; }
        public int ReportReasonId { get; set; }
        public bool IsHandled { get; set; }

        public virtual CommentsAttraction CommentAttraction { get; set; }
        public virtual ReportReason ReportReason { get; set; }
    }
}