// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class ReportReason
    {
        public ReportReason()
        {
            ReportedAttractionComments = new HashSet<ReportedAttractionComment>();
        }

        public int Id { get; set; }
        public string Reason { get; set; }

        public virtual ICollection<ReportedAttractionComment> ReportedAttractionComments { get; set; }
    }
}