// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class RoomProduct
    {
        public RoomProduct()
        {
            CartAccommodationDetails = new HashSet<CartAccommodationDetail>();
            OrderAccommodationDetails = new HashSet<OrderAccommodationDetail>();
        }

        public int Id { get; set; }
        public int RoomId { get; set; }
        public DateTime Date { get; set; }
        public decimal NewPrice { get; set; }
        public int Quantity { get; set; }

        public virtual Room Room { get; set; }
        public virtual ICollection<CartAccommodationDetail> CartAccommodationDetails { get; set; }
        public virtual ICollection<OrderAccommodationDetail> OrderAccommodationDetails { get; set; }
    }
}