// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class RoomServiceInfo
    {
        public RoomServiceInfo()
        {
            Rooms = new HashSet<Room>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? ServiceInfoCategoryId { get; set; }

        public virtual ServiceInfoCategory ServiceInfoCategory { get; set; }

        public virtual ICollection<Room> Rooms { get; set; }
    }
}