// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class SystemMessage
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string Content { get; set; }
        public bool IsRead { get; set; }

        public virtual Member Member { get; set; }
    }
}