// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterBackend.Models
{
    public partial class Town
    {
        public Town()
        {
            Accommodations = new HashSet<Accommodation>();
            Attractions = new HashSet<Attraction>();
        }

        public int Id { get; set; }
        public int RegionId { get; set; }
        public string Name { get; set; }

        public virtual Region Region { get; set; }
        public virtual ICollection<Accommodation> Accommodations { get; set; }
        public virtual ICollection<Attraction> Attractions { get; set; }
    }
}