// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class AccommodationServiceInfo
    {
        public AccommodationServiceInfo()
        {
            Accommodations = new HashSet<Accommodation>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int ServiceInfoCategoryId { get; set; }

        public virtual ServiceInfoCategory ServiceInfoCategory { get; set; }

        public virtual ICollection<Accommodation> Accommodations { get; set; }
    }
}