// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class ActivityImage
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public string Image { get; set; }

        public virtual Activity Activity { get; set; }
    }
}