// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class AttractionTag
    {
        public AttractionTag()
        {
            Attractions = new HashSet<Attraction>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Attraction> Attractions { get; set; }
    }
}