// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class Cart
    {
        public Cart()
        {
            Cart_AccommodationDetails = new HashSet<Cart_AccommodationDetail>();
            Cart_ActivitiesDetails = new HashSet<Cart_ActivitiesDetail>();
            Cart_ExtraServicesDetails = new HashSet<Cart_ExtraServicesDetail>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }

        public virtual Member Member { get; set; }
        public virtual ICollection<Cart_AccommodationDetail> Cart_AccommodationDetails { get; set; }
        public virtual ICollection<Cart_ActivitiesDetail> Cart_ActivitiesDetails { get; set; }
        public virtual ICollection<Cart_ExtraServicesDetail> Cart_ExtraServicesDetails { get; set; }
    }
}