// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class Comments_Accommodation
    {
        public Comments_Accommodation()
        {
            Comment_Accommodation_Likes = new HashSet<Comment_Accommodation_Like>();
            Comments_AccommodationImages = new HashSet<Comments_AccommodationImage>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public int AccommodationId { get; set; }
        public int Score { get; set; }
        public string Title { get; set; }
        public string Pros { get; set; }
        public string Cons { get; set; }
        public DateTime CreateDate { get; set; }
        public int CommentStatusId { get; set; }
        public string Reply { get; set; }
        public DateTime? ReplyAt { get; set; }

        public virtual Accommodation Accommodation { get; set; }
        public virtual CommentStatus CommentStatus { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Comment_Accommodation_Like> Comment_Accommodation_Likes { get; set; }
        public virtual ICollection<Comments_AccommodationImage> Comments_AccommodationImages { get; set; }
    }
}