// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class Comments_AccommodationImage
    {
        public int Id { get; set; }
        public int Comments_AccommodationId { get; set; }
        public string Image { get; set; }

        public virtual Comments_Accommodation Comments_Accommodation { get; set; }
    }
}