// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class CommentStatus
    {
        public CommentStatus()
        {
            Comments_Accommodations = new HashSet<Comments_Accommodation>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Comments_Accommodation> Comments_Accommodations { get; set; }
    }
}