// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class FAQCategory
    {
        public FAQCategory()
        {
            FAQs = new HashSet<FAQ>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<FAQ> FAQs { get; set; }
    }
}