// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class OrderExtraServicesDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ExtraServiceId { get; set; }
        public string ExtraServiceName { get; set; }
        public int ExtraServiceProductId { get; set; }
        public DateTime Date { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }

        public virtual ExtraService ExtraService { get; set; }
        public virtual ExtraServiceProduct ExtraServiceProduct { get; set; }
        public virtual Order Order { get; set; }
    }
}