// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class PackageCoupon
    {
        public PackageCoupon()
        {
            PackageTours = new HashSet<PackageTour>();
        }

        public int Id { get; set; }
        public double Discount { get; set; }

        public virtual ICollection<PackageTour> PackageTours { get; set; }
    }
}