// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class Partner
    {
        public Partner()
        {
            Accommodations = new HashSet<Accommodation>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EncryptedPassword { get; set; }
        public string Email { get; set; }
        public DateTime CreateDate { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmCode { get; set; }
        public string GoogleAccessCode { get; set; }
        public string FaceBookAccessCode { get; set; }
        public string LineAccessCode { get; set; }
        public DateTime? LoginTime { get; set; }
        public bool IsSuspended { get; set; }

        public virtual ICollection<Accommodation> Accommodations { get; set; }
    }
}