// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class RoomProduct
    {
        public RoomProduct()
        {
            Cart_AccommodationDetails = new HashSet<Cart_AccommodationDetail>();
            OrderAccommodationDetails = new HashSet<OrderAccommodationDetail>();
        }

        public int Id { get; set; }
        public int RoomId { get; set; }
        public DateTime Date { get; set; }
        public decimal NewPrice { get; set; }
        public int Quantity { get; set; }

        public virtual Room Room { get; set; }
        public virtual ICollection<Cart_AccommodationDetail> Cart_AccommodationDetails { get; set; }
        public virtual ICollection<OrderAccommodationDetail> OrderAccommodationDetails { get; set; }
    }
}