// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RouteMasterFrontend.EFModels
{
    public partial class RouteMasterContext : DbContext
    {
        public RouteMasterContext()
        {
        }

        public RouteMasterContext(DbContextOptions<RouteMasterContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<AccommodationImage> AccommodationImages { get; set; }
        public virtual DbSet<AccommodationServiceInfo> AccommodationServiceInfos { get; set; }
        public virtual DbSet<AcommodationCategory> AcommodationCategories { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategories { get; set; }
        public virtual DbSet<ActivityImage> ActivityImages { get; set; }
        public virtual DbSet<ActivityProduct> ActivityProducts { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Attraction> Attractions { get; set; }
        public virtual DbSet<AttractionCategory> AttractionCategories { get; set; }
        public virtual DbSet<AttractionClick> AttractionClicks { get; set; }
        public virtual DbSet<AttractionImage> AttractionImages { get; set; }
        public virtual DbSet<AttractionTag> AttractionTags { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart_AccommodationDetail> Cart_AccommodationDetails { get; set; }
        public virtual DbSet<Cart_ActivitiesDetail> Cart_ActivitiesDetails { get; set; }
        public virtual DbSet<Cart_ExtraServicesDetail> Cart_ExtraServicesDetails { get; set; }
        public virtual DbSet<CommentStatus> CommentStatuses { get; set; }
        public virtual DbSet<Comment_Accommodation_Like> Comment_Accommodation_Likes { get; set; }
        public virtual DbSet<Comments_Accommodation> Comments_Accommodations { get; set; }
        public virtual DbSet<Comments_AccommodationImage> Comments_AccommodationImages { get; set; }
        public virtual DbSet<Comments_Attraction> Comments_Attractions { get; set; }
        public virtual DbSet<Comments_AttractionImage> Comments_AttractionImages { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<ExtraService> ExtraServices { get; set; }
        public virtual DbSet<ExtraServiceImage> ExtraServiceImages { get; set; }
        public virtual DbSet<ExtraServiceProduct> ExtraServiceProducts { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FAQCategory> FAQCategories { get; set; }
        public virtual DbSet<FavoriteAttraction> FavoriteAttractions { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberImage> MemberImages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderAccommodationDetail> OrderAccommodationDetails { get; set; }
        public virtual DbSet<OrderActivitiesDetail> OrderActivitiesDetails { get; set; }
        public virtual DbSet<OrderExtraServicesDetail> OrderExtraServicesDetails { get; set; }
        public virtual DbSet<OrderHandleStatus> OrderHandleStatuses { get; set; }
        public virtual DbSet<PackageCoupon> PackageCoupons { get; set; }
        public virtual DbSet<PackageTour> PackageTours { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<ReportReason> ReportReasons { get; set; }
        public virtual DbSet<ReportedAttractionComment> ReportedAttractionComments { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomImage> RoomImages { get; set; }
        public virtual DbSet<RoomProduct> RoomProducts { get; set; }
        public virtual DbSet<RoomServiceInfo> RoomServiceInfos { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ServiceInfoCategory> ServiceInfoCategories { get; set; }
        public virtual DbSet<SystemImage> SystemImages { get; set; }
        public virtual DbSet<SystemMessage> SystemMessages { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<Transportation> Transportations { get; set; }
        public virtual DbSet<TravelPlan> TravelPlans { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=RouteMaster;User ID=sa5;Password=sa5");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Accommodation>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description).HasMaxLength(2000);

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.IndustryEmail).HasMaxLength(255);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.PhoneNumber).HasMaxLength(20);

                entity.Property(e => e.Website).HasMaxLength(2000);

                entity.HasOne(d => d.AcommodationCategory)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.AcommodationCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Acomm__47A6A41B");

                entity.HasOne(d => d.Partner)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.PartnerId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Partn__489AC854");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Regio__498EEC8D");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.Accommodations)
                    .HasForeignKey(d => d.TownId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__TownI__4A8310C6");

                entity.HasMany(d => d.AccommodationServiceInfos)
                    .WithMany(p => p.Accommodations)
                    .UsingEntity<Dictionary<string, object>>(
                        "AccommodationServiceInfos_Accommodation",
                        l => l.HasOne<AccommodationServiceInfo>().WithMany().HasForeignKey("AccommodationServiceInfoId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__ServiceIn__Accom__0F2D40CE"),
                        r => r.HasOne<Accommodation>().WithMany().HasForeignKey("AccommodationId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Accommoda__Accom__4C6B5938"),
                        j =>
                        {
                            j.HasKey("AccommodationId", "AccommodationServiceInfoId").HasName("PK__Accommod__DE629F1B7827F3C8");

                            j.ToTable("AccommodationServiceInfos_Accommodations");
                        });
            });

            modelBuilder.Entity<AccommodationImage>(entity =>
            {
                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.AccommodationImages)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Accommoda__Accom__46B27FE2");
            });

            modelBuilder.Entity<AccommodationServiceInfo>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.ServiceInfoCategory)
                    .WithMany(p => p.AccommodationServiceInfos)
                    .HasForeignKey(d => d.ServiceInfoCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_AccommodationServiceInfos_ServiceInfoCategories");
            });

            modelBuilder.Entity<AcommodationCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Activity>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.ActivityCategory)
                    .WithMany(p => p.Activities)
                    .HasForeignKey(d => d.ActivityCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activitie__Activ__4E53A1AA");

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.Activities)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activitie__Attra__4F47C5E3");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Activities)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activitie__Regio__503BEA1C");
            });

            modelBuilder.Entity<ActivityCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<ActivityImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.ActivityImages)
                    .HasForeignKey(d => d.ActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ActivityI__Activ__51300E55");
            });

            modelBuilder.Entity<ActivityProduct>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.ActivityProducts)
                    .HasForeignKey(d => d.ActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ActivityP__Activ__5224328E");
            });

            modelBuilder.Entity<Administrator>(entity =>
            {
                entity.HasIndex(e => e.Email, "UQ__Administ__A9D10534E74307ED")
                    .IsUnique();

                entity.Property(e => e.ConfirmCode).HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.EncryptedPassword)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.Permission)
                    .WithMany(p => p.Administrators)
                    .HasForeignKey(d => d.PermissionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Administr__Permi__531856C7");
            });

            modelBuilder.Entity<Attraction>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Website).HasMaxLength(2000);

                entity.HasOne(d => d.AttractionCategory)
                    .WithMany(p => p.Attractions)
                    .HasForeignKey(d => d.AttractionCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Attra__55F4C372");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Attractions)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Regio__56E8E7AB");

                entity.HasOne(d => d.Town)
                    .WithMany(p => p.Attractions)
                    .HasForeignKey(d => d.TownId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__TownI__57DD0BE4");

                entity.HasMany(d => d.Tags)
                    .WithMany(p => p.Attractions)
                    .UsingEntity<Dictionary<string, object>>(
                        "Tags_Attraction",
                        l => l.HasOne<AttractionTag>().WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Tags_Attr__TagId__15DA3E5D"),
                        r => r.HasOne<Attraction>().WithMany().HasForeignKey("AttractionId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Tags_Attr__Attra__14E61A24"),
                        j =>
                        {
                            j.HasKey("AttractionId", "TagId").HasName("PK__Tags_Att__0CB582C0B1405FFE");

                            j.ToTable("Tags_Attractions");
                        });
            });

            modelBuilder.Entity<AttractionCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<AttractionClick>(entity =>
            {
                entity.ToTable("AttractionClick");

                entity.Property(e => e.ClickDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.AttractionClicks)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Attra__540C7B00");
            });

            modelBuilder.Entity<AttractionImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.AttractionImages)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Attractio__Attra__55009F39");
            });

            modelBuilder.Entity<AttractionTag>(entity =>
            {
                entity.Property(e => e.Name).HasMaxLength(50);
            });

            modelBuilder.Entity<Cart>(entity =>
            {
                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Carts)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Carts__MemberId__5E8A0973");
            });

            modelBuilder.Entity<Cart_AccommodationDetail>(entity =>
            {
                entity.HasOne(d => d.Cart)
                    .WithMany(p => p.Cart_AccommodationDetails)
                    .HasForeignKey(d => d.CartId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acco__CartI__58D1301D");

                entity.HasOne(d => d.RoomProduct)
                    .WithMany(p => p.Cart_AccommodationDetails)
                    .HasForeignKey(d => d.RoomProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acco__RoomP__59C55456");
            });

            modelBuilder.Entity<Cart_ActivitiesDetail>(entity =>
            {
                entity.HasOne(d => d.ActivityProduct)
                    .WithMany(p => p.Cart_ActivitiesDetails)
                    .HasForeignKey(d => d.ActivityProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acti__Activ__5AB9788F");

                entity.HasOne(d => d.Cart)
                    .WithMany(p => p.Cart_ActivitiesDetails)
                    .HasForeignKey(d => d.CartId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Acti__CartI__5BAD9CC8");
            });

            modelBuilder.Entity<Cart_ExtraServicesDetail>(entity =>
            {
                entity.HasOne(d => d.Cart)
                    .WithMany(p => p.Cart_ExtraServicesDetails)
                    .HasForeignKey(d => d.CartId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Extr__CartI__5CA1C101");

                entity.HasOne(d => d.ExtraServiceProduct)
                    .WithMany(p => p.Cart_ExtraServicesDetails)
                    .HasForeignKey(d => d.ExtraServiceProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Cart_Extr__Extra__5D95E53A");
            });

            modelBuilder.Entity<CommentStatus>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Comment_Accommodation_Like>(entity =>
            {
                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Comments_Accommodation)
                    .WithMany(p => p.Comment_Accommodation_Likes)
                    .HasForeignKey(d => d.Comments_AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comment_A__Comme__5F7E2DAC");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Comment_Accommodation_Likes)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comment_A__Membe__607251E5");
            });

            modelBuilder.Entity<Comments_Accommodation>(entity =>
            {
                entity.Property(e => e.Cons).HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Pros).HasMaxLength(2000);

                entity.Property(e => e.Reply).HasMaxLength(2000);

                entity.Property(e => e.ReplyAt).HasColumnType("datetime");

                entity.Property(e => e.Title).HasMaxLength(50);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.Comments_Accommodations)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Accom__625A9A57");

                entity.HasOne(d => d.CommentStatus)
                    .WithMany(p => p.Comments_Accommodations)
                    .HasForeignKey(d => d.CommentStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Comme__634EBE90");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Comments_Accommodations)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Membe__6442E2C9");
            });

            modelBuilder.Entity<Comments_AccommodationImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Comments_Accommodation)
                    .WithMany(p => p.Comments_AccommodationImages)
                    .HasForeignKey(d => d.Comments_AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Comme__6166761E");
            });

            modelBuilder.Entity<Comments_Attraction>(entity =>
            {
                entity.Property(e => e.Content).HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.Comments_Attractions)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Attra__662B2B3B");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Comments_Attractions)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Membe__671F4F74");
            });

            modelBuilder.Entity<Comments_AttractionImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Comments_Attraction)
                    .WithMany(p => p.Comments_AttractionImages)
                    .HasForeignKey(d => d.Comments_AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Comments___Comme__65370702");
            });

            modelBuilder.Entity<Coupon>(entity =>
            {
                entity.Property(e => e.EndDate).HasColumnType("datetime");

                entity.Property(e => e.StartDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<ExtraService>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.ExtraServices)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Attra__69FBBC1F");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.ExtraServices)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Regio__6AEFE058");
            });

            modelBuilder.Entity<ExtraServiceImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.ExtraService)
                    .WithMany(p => p.ExtraServiceImages)
                    .HasForeignKey(d => d.ExtraServiceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Extra__681373AD");
            });

            modelBuilder.Entity<ExtraServiceProduct>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.ExtraService)
                    .WithMany(p => p.ExtraServiceProducts)
                    .HasForeignKey(d => d.ExtraServiceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ExtraServ__Extra__690797E6");
            });

            modelBuilder.Entity<FAQ>(entity =>
            {
                entity.Property(e => e.Answer)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.Question)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.HasOne(d => d.FAQCategory)
                    .WithMany(p => p.FAQs)
                    .HasForeignKey(d => d.FAQCategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__FAQs__FAQCategor__6BE40491");
            });

            modelBuilder.Entity<FAQCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<FavoriteAttraction>(entity =>
            {
                entity.HasOne(d => d.Attraction)
                    .WithMany(p => p.FavoriteAttractions)
                    .HasForeignKey(d => d.AttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__FavoriteA__Attra__6CD828CA");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.FavoriteAttractions)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__FavoriteA__Membe__6DCC4D03");
            });

            modelBuilder.Entity<Member>(entity =>
            {
                entity.HasIndex(e => e.Email, "UQ__Members__A9D1053492362E04")
                    .IsUnique();

                entity.HasIndex(e => e.Account, "UQ__Members__B0C3AC460F60ED2B")
                    .IsUnique();

                entity.Property(e => e.Account)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Address).HasMaxLength(255);

                entity.Property(e => e.Birthday).HasColumnType("datetime");

                entity.Property(e => e.CellPhoneNumber).HasMaxLength(10);

                entity.Property(e => e.ConfirmCode).HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.EncryptedPassword).HasMaxLength(255);

                entity.Property(e => e.FaceBookAccessCode).HasMaxLength(300);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.GoogleAccessCode).HasMaxLength(300);

                entity.Property(e => e.Image).HasMaxLength(200);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LineAccessCode).HasMaxLength(300);

                entity.Property(e => e.LoginTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<MemberImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.MemberImages)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__MemberIma__Membe__6EC0713C");
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.HasOne(d => d.Coupons)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.CouponsId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__CouponsI__7849DB76");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__MemberId__793DFFAF");

                entity.HasOne(d => d.OrderHandleStatus)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.OrderHandleStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__OrderHan__7A3223E8");

                entity.HasOne(d => d.PaymentMethod)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.PaymentMethodId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__PaymentM__7B264821");

                entity.HasOne(d => d.PaymentStatus)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.PaymentStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Orders__PaymentS__7C1A6C5A");
            });

            modelBuilder.Entity<OrderAccommodationDetail>(entity =>
            {
                entity.Property(e => e.AccommodationName).HasMaxLength(50);

                entity.Property(e => e.CheckIn).HasColumnType("datetime");

                entity.Property(e => e.CheckOut).HasColumnType("datetime");

                entity.Property(e => e.Note).HasMaxLength(2000);

                entity.Property(e => e.RoomName).HasMaxLength(50);

                entity.Property(e => e.RoomType).HasMaxLength(50);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.OrderAccommodationDetails)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderAcco__Accom__6FB49575");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderAccommodationDetails)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderAcco__Order__70A8B9AE");

                entity.HasOne(d => d.RoomProduct)
                    .WithMany(p => p.OrderAccommodationDetails)
                    .HasForeignKey(d => d.RoomProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderAcco__RoomP__719CDDE7");
            });

            modelBuilder.Entity<OrderActivitiesDetail>(entity =>
            {
                entity.Property(e => e.ActivityName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Date).HasColumnType("date");

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.OrderActivitiesDetails)
                    .HasForeignKey(d => d.ActivityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderActi__Activ__72910220");

                entity.HasOne(d => d.ActivityProduct)
                    .WithMany(p => p.OrderActivitiesDetails)
                    .HasForeignKey(d => d.ActivityProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderActi__Activ__73852659");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderActivitiesDetails)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderActi__Order__74794A92");
            });

            modelBuilder.Entity<OrderExtraServicesDetail>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.Property(e => e.ExtraServiceName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.ExtraService)
                    .WithMany(p => p.OrderExtraServicesDetails)
                    .HasForeignKey(d => d.ExtraServiceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderExtr__Extra__756D6ECB");

                entity.HasOne(d => d.ExtraServiceProduct)
                    .WithMany(p => p.OrderExtraServicesDetails)
                    .HasForeignKey(d => d.ExtraServiceProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderExtr__Extra__76619304");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderExtraServicesDetails)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderExtr__Order__7755B73D");
            });

            modelBuilder.Entity<OrderHandleStatus>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<PackageTour>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.HasOne(d => d.PackageCoupon)
                    .WithMany(p => p.PackageTours)
                    .HasForeignKey(d => d.PackageCouponId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__PackageTo__Packa__03BB8E22");

                entity.HasMany(d => d.Activities)
                    .WithMany(p => p.PackageTours)
                    .UsingEntity<Dictionary<string, object>>(
                        "PackageActivity",
                        l => l.HasOne<Activity>().WithMany().HasForeignKey("ActivityId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAc__Activ__7E02B4CC"),
                        r => r.HasOne<PackageTour>().WithMany().HasForeignKey("PackageTourId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAc__Packa__7EF6D905"),
                        j =>
                        {
                            j.HasKey("PackageTourId", "ActivityId").HasName("PK__PackageA__95FB0D54F413BDF5");

                            j.ToTable("PackageActivities");
                        });

                entity.HasMany(d => d.Attractions)
                    .WithMany(p => p.PackageTours)
                    .UsingEntity<Dictionary<string, object>>(
                        "PackageAttraction",
                        l => l.HasOne<Attraction>().WithMany().HasForeignKey("AttractionId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAt__Attra__7FEAFD3E"),
                        r => r.HasOne<PackageTour>().WithMany().HasForeignKey("PackageTourId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageAt__Packa__00DF2177"),
                        j =>
                        {
                            j.HasKey("PackageTourId", "AttractionId").HasName("PK__PackageA__2C0A63F8830BBA8B");

                            j.ToTable("PackageAttractions");
                        });

                entity.HasMany(d => d.ExtraServices)
                    .WithMany(p => p.PackageTours)
                    .UsingEntity<Dictionary<string, object>>(
                        "PackageExtraService",
                        l => l.HasOne<ExtraService>().WithMany().HasForeignKey("ExtraServiceId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageEx__Extra__01D345B0"),
                        r => r.HasOne<PackageTour>().WithMany().HasForeignKey("PackageTourId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PackageEx__Packa__02C769E9"),
                        j =>
                        {
                            j.HasKey("PackageTourId", "ExtraServiceId").HasName("PK__PackageE__0943AA6213C7E40A");

                            j.ToTable("PackageExtraServices");
                        });
            });

            modelBuilder.Entity<Partner>(entity =>
            {
                entity.HasIndex(e => e.Email, "UQ__Partners__A9D1053473FBDA8E")
                    .IsUnique();

                entity.Property(e => e.ConfirmCode).HasMaxLength(300);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.EncryptedPassword).HasMaxLength(255);

                entity.Property(e => e.FaceBookAccessCode).HasMaxLength(300);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.GoogleAccessCode).HasMaxLength(300);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LineAccessCode).HasMaxLength(300);

                entity.Property(e => e.LoginTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<PaymentMethod>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<PaymentStatus>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Permission>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Region>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<ReportReason>(entity =>
            {
                entity.Property(e => e.Reason).HasMaxLength(50);
            });

            modelBuilder.Entity<ReportedAttractionComment>(entity =>
            {
                entity.HasOne(d => d.CommentAttraction)
                    .WithMany(p => p.ReportedAttractionComments)
                    .HasForeignKey(d => d.CommentAttractionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ReportedA__Comme__0A688BB1");

                entity.HasOne(d => d.ReportReason)
                    .WithMany(p => p.ReportedAttractionComments)
                    .HasForeignKey(d => d.ReportReasonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ReportedA__Repor__0B5CAFEA");
            });

            modelBuilder.Entity<Room>(entity =>
            {
                entity.Property(e => e.Description).HasMaxLength(2000);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Accommodation)
                    .WithMany(p => p.Rooms)
                    .HasForeignKey(d => d.AccommodationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Rooms__Accommoda__0E391C95");

                entity.HasOne(d => d.RoomType)
                    .WithMany(p => p.Rooms)
                    .HasForeignKey(d => d.RoomTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Rooms__RoomTypeI__0F2D40CE");

                entity.HasMany(d => d.RoomServiceInfos)
                    .WithMany(p => p.Rooms)
                    .UsingEntity<Dictionary<string, object>>(
                        "RoomServiceInfos_Room",
                        l => l.HasOne<RoomServiceInfo>().WithMany().HasForeignKey("RoomServiceInfoId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__RoomServi__RoomS__1209AD79"),
                        r => r.HasOne<Room>().WithMany().HasForeignKey("RoomId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__RoomServi__RoomI__11158940"),
                        j =>
                        {
                            j.HasKey("RoomId", "RoomServiceInfoId").HasName("PK__RoomServ__B47A7613838EDBF8");

                            j.ToTable("RoomServiceInfos_Rooms");
                        });
            });

            modelBuilder.Entity<RoomImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Room)
                    .WithMany(p => p.RoomImages)
                    .HasForeignKey(d => d.RoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__RoomImage__RoomI__0C50D423");
            });

            modelBuilder.Entity<RoomProduct>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("date");

                entity.Property(e => e.NewPrice).HasColumnType("decimal(18, 0)");

                entity.HasOne(d => d.Room)
                    .WithMany(p => p.RoomProducts)
                    .HasForeignKey(d => d.RoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__RoomProdu__RoomI__0D44F85C");
            });

            modelBuilder.Entity<RoomServiceInfo>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.ServiceInfoCategory)
                    .WithMany(p => p.RoomServiceInfos)
                    .HasForeignKey(d => d.ServiceInfoCategoryId)
                    .HasConstraintName("FK_RoomServiceInfos_ServiceInfoCategories");
            });

            modelBuilder.Entity<RoomType>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<Schedule>(entity =>
            {
                entity.Property(e => e.Content)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.EndTime).HasColumnType("datetime");

                entity.Property(e => e.StartTime).HasColumnType("datetime");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Schedules)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Schedules__Membe__12FDD1B2");
            });

            modelBuilder.Entity<ServiceInfoCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<SystemImage>(entity =>
            {
                entity.Property(e => e.Image)
                    .IsRequired()
                    .HasMaxLength(200);
            });

            modelBuilder.Entity<SystemMessage>(entity =>
            {
                entity.Property(e => e.Content)
                    .IsRequired()
                    .HasMaxLength(2000);

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.SystemMessages)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__SystemMes__Membe__13F1F5EB");
            });

            modelBuilder.Entity<Town>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.Towns)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Towns__RegionId__16CE6296");
            });

            modelBuilder.Entity<Transportation>(entity =>
            {
                entity.ToTable("Transportation");

                entity.Property(e => e.Arrival)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Departure)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Vehicle)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.TravelPlan)
                    .WithMany(p => p.Transportations)
                    .HasForeignKey(d => d.TravelPlanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Transport__Trave__17C286CF");
            });

            modelBuilder.Entity<TravelPlan>(entity =>
            {
                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.TravelPlans)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TravelPla__Membe__18B6AB08");

                entity.HasMany(d => d.ActivityProducts)
                    .WithMany(p => p.TravelPlans)
                    .UsingEntity<Dictionary<string, object>>(
                        "PlanActivity",
                        l => l.HasOne<ActivityProduct>().WithMany().HasForeignKey("ActivityProductId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanActiv__Activ__04AFB25B"),
                        r => r.HasOne<TravelPlan>().WithMany().HasForeignKey("TravelPlanId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanActiv__Trave__05A3D694"),
                        j =>
                        {
                            j.HasKey("TravelPlanId", "ActivityProductId").HasName("PK__PlanActi__EB02F9A02E9DAB0B");

                            j.ToTable("PlanActivities");
                        });

                entity.HasMany(d => d.Attractions)
                    .WithMany(p => p.TravelPlans)
                    .UsingEntity<Dictionary<string, object>>(
                        "PlanAttraction",
                        l => l.HasOne<Attraction>().WithMany().HasForeignKey("AttractionId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanAttra__Attra__0697FACD"),
                        r => r.HasOne<TravelPlan>().WithMany().HasForeignKey("TravelPlanId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanAttra__Trave__078C1F06"),
                        j =>
                        {
                            j.HasKey("TravelPlanId", "AttractionId").HasName("PK__PlanAttr__99DDD1EEE327E1D3");

                            j.ToTable("PlanAttractions");
                        });

                entity.HasMany(d => d.ExtraServiceProducts)
                    .WithMany(p => p.TravelPlans)
                    .UsingEntity<Dictionary<string, object>>(
                        "PlanExtraService",
                        l => l.HasOne<ExtraServiceProduct>().WithMany().HasForeignKey("ExtraServiceProductId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanExtra__Extra__0880433F"),
                        r => r.HasOne<TravelPlan>().WithMany().HasForeignKey("TravelPlanId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__PlanExtra__Trave__09746778"),
                        j =>
                        {
                            j.HasKey("TravelPlanId", "ExtraServiceProductId").HasName("PK__PlanExtr__4FFE2B653BA06987");

                            j.ToTable("PlanExtraServices");
                        });
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}