// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.EFModels
{
    public partial class ServiceInfoCategory
    {
        public ServiceInfoCategory()
        {
            AccommodationServiceInfos = new HashSet<AccommodationServiceInfo>();
            RoomServiceInfos = new HashSet<RoomServiceInfo>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<AccommodationServiceInfo> AccommodationServiceInfos { get; set; }
        public virtual ICollection<RoomServiceInfo> RoomServiceInfos { get; set; }
    }
}